---
# Separate the workflow for actionlint to other workflows, because if a workflow for actionlint is broken actionlint isn't run
name: actionlint
on:
  pull_request:
    paths:
      - .github/workflows/*.yaml
env:
  PRE_COMMIT_COLOR: always
jobs:
  actionlint:
    timeout-minutes: 30
    runs-on: "ubuntu-22.04"
    permissions: {}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@87e8236f46702ab0ce5a058b605a173ec88d618e # v6
      - name: check ghalint version
        run: |
          nix build .#ghalint
          ./result/bin/ghalint --version
      - name: run actionlint
        run: |
          nix develop --command pre-commit run actionlint --all-files
      - name: run ghalint
        run: |
          nix develop --command pre-commit run ghalint --all-files

