---
name: Pull Request
on: pull_request
env:
  PRE_COMMIT_COLOR: always
permissions: {}
jobs:
  add-label:
    permissions:
      contents: read
    uses: murn0/auto-add-labels-workflow/.github/workflows/main.yaml@f97918aeaeddccf4be0689d48f05b82403c21586 # v0.4.1
    secrets:
      gh_app_id: ${{secrets.GH_APP_ID}}
      gh_app_private_key: ${{secrets.GH_APP_PRIVATE_KEY}}

  path-filter:
    timeout-minutes: 10
    runs-on: "ubuntu-22.04"
    outputs:
      renovate-config-validator: ${{steps.changes.outputs.renovate-config-validator}}
      renovate-config-validator-files: ${{ steps.changes.outputs.renovate-config-validator_files }}
    permissions: {}
    steps:
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          list-files: shell
          filters: |
            renovate-config-validator:
              - default.json
              - renovate.json
              - .github/workflows/pull_request.yaml

  renovate-config-validator:
    uses: ./.github/workflows/wc-renovate-config-validator.yaml
    needs: path-filter
    if: needs.path-filter.outputs.renovate-config-validator == 'true'
    permissions: {}
    with:
      changed-files: ${{needs.path-filter.outputs.renovate-config-validator-files}}
