name: Generate release
on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions: {}
jobs:
  generate-release:
    uses: murn0/generate-release-workflow/.github/workflows/wc-generate-release.yaml@3d4ed1b8620894318b7d43689cd3aeb2e999e8cb # v0.7.0
    permissions:
      issues: write
    if: |
      github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/v')
    with:
      draft: true
    secrets:
      gh_app_id: ${{secrets.GH_APP_ID}}
      gh_app_private_key: ${{secrets.GH_APP_PRIVATE_KEY}}