name: Generate release
on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions: {}
jobs:
  generate-release:
    uses: murn0/generate-release-workflow/.github/workflows/wc-generate-release.yaml@f6760a54ffed12ee20ba6a9f58e46c1884baf1a7 # v0.6.1
    permissions:
      issues: write
    if: |
      github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/v')
    with:
      draft: true
    secrets:
      gh_app_id: ${{secrets.GH_APP_ID}}
      gh_app_private_key: ${{secrets.GH_APP_PRIVATE_KEY}}