---
name: Pull Request
on: pull_request
permissions: {}
jobs:
  flake-check:
    timeout-minutes: 30
    runs-on: "ubuntu-latest"
    permissions: {}
    env:
      PRE_COMMIT_COLOR: always
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@87e8236f46702ab0ce5a058b605a173ec88d618e # v6
      - name: run nix flake check
        run: |
          nix flake check --impure

  enable-automerge:
    timeout-minutes: 30
    runs-on: "ubuntu-latest"
    needs:
      - flake-check
    permissions:
      contents: write # For enable automerge
      pull-requests: write # For enable automerge
    # "! failure() && ! cancelled()" is required. success() returns false if dependent jobs are skipped.
    # https://github.com/community/community/discussions/45058
    # By default success() is used so we have to override success() by "! failure() && ! cancelled()"
    if: |
      ! failure() && ! cancelled() && github.event.pull_request.user.login == 'renovate[bot]' && contains(github.event.pull_request.body, ' **Automerge**: Enabled.')
    steps:
      - name: merge pull request
        run: gh -R "$GITHUB_REPOSITORY" pr merge --squash --delete-branch "${{github.event.pull_request.number}}"
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
