---
name: enable-auto-merge
on:
  workflow_call:
    inputs:
      merge-method:
        required: false
        type: string
        default: merge
        description: |
          merge, squash, rebaseのいずれか設定
    secrets:
      gh_app_id:
        required: true
      gh_app_private_key:
        required: true
jobs:
  enable-auto-merge:
    timeout-minutes: 30
    # Enable automerge to merge pull requests from Renovate automatically.
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: check merge method
        shell: bash
        run: |
          if [ "$MERGE_METHOD" = merge ] || [ "$MERGE_METHOD" = squash ] || [ "$MERGE_METHOD" = rebase ]; then
            exit 0
          fi
          echo "::error :: inputs.merge-method にはmerge, squash rebaseのいずれかを設定して下さい"
          exit 1
        env:
          MERGE_METHOD: ${{inputs.merge-method}}
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@32691ba7c9e7063bd457bd8f2a5703138591fa58 # v1.9.0
        with:
          app_id: ${{secrets.gh_app_id}}
          private_key: ${{secrets.gh_app_private_key}}
          permissions: >-
            {
              "contents": "write",
              "pull_requests": "write"
            }
          repositories: >-
            [
              "${{github.event.repository.name}}"
            ]
      - run: gh -R "$GITHUB_REPOSITORY" pr merge --${{inputs.merge-method}} --auto --delete-branch "$PR_NUMBER"
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}} # Use GitHub App to trigger GitHub Actions Workflow by merge commit.
          PR_NUMBER: ${{github.event.pull_request.number}}
