---
name: status-check
on: workflow_call
jobs:
  status-check:
    # このジョブは、メインブランチのブランチ保護ルールのステータスチェックに使用されます。
    # すべての依存ジョブが成功するかスキップされた場合、このジョブは成功します。
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - run: exit 1
